# Basic Auth Secret for Test 20
# NGINX equivalent annotations:
#   nginx.ingress.kubernetes.io/auth-type: basic
#   nginx.ingress.kubernetes.io/auth-secret: basic-auth
#   nginx.ingress.kubernetes.io/auth-realm: "Authentication Required" (cosmetic)
#
# htpasswd format: username:{SHA}base64_encoded_sha1_hash
# Test users:
#   - basicuser:basicpass (SHA1 hash)
#   - admin:adminpass (SHA1 hash)
#
# Generate SHA1 hash: echo -n "password" | openssl dgst -sha1 -binary | base64

apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: ingress2kgateway
  labels:
    app: basic-auth-test
    test: basic-auth-20
type: Opaque
stringData:
  # htpasswd format with SHA1 hashes
  # Generate: echo -n "password" | openssl dgst -sha1 -binary | base64
  # basicuser:basicpass -> {SHA}pseq98bTMdvEj1owVo0r7UkW2aE=
  # admin:adminpass -> {SHA}dJE/XNX2HsC8/bd1QUwvs9FhtiA=
  .htpasswd: |
    basicuser:{SHA}pseq98bTMdvEj1owVo0r7UkW2aE=
    admin:{SHA}dJE/XNX2HsC8/bd1QUwvs9FhtiA=
