# Echo Server - Primary test backend
# Returns request details as JSON (headers, path, method, etc.)
# 3 replicas for testing load balancing and session affinity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: ingress2envoygateway
  labels:
    app: echo-server
    version: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-server
      version: stable
  template:
    metadata:
      labels:
        app: echo-server
        version: stable
    spec:
      containers:
      - name: echo-server
        image: ealen/echo-server:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: VERSION
          value: "stable"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: ingress2envoygateway
  labels:
    app: echo-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echo-server
    version: stable
---
# LoadBalancer service for testing load balancing algorithms
apiVersion: v1
kind: Service
metadata:
  name: echo-server-lb
  namespace: ingress2envoygateway
  labels:
    app: echo-server
    test: load-balancer
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echo-server
    version: stable
