# Echo Server Canary - For testing weighted traffic splitting
# 2 replicas with VERSION=canary label
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-canary
  namespace: ingress2envoygateway
  labels:
    app: echo-server
    version: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
      version: canary
  template:
    metadata:
      labels:
        app: echo-server
        version: canary
    spec:
      containers:
      - name: echo-server
        image: ealen/echo-server:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: VERSION
          value: "canary"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-canary
  namespace: ingress2envoygateway
  labels:
    app: echo-server
    version: canary
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echo-server
    version: canary
