# HTTPRouteFilter for Direct Response
# Ref: https://gateway.envoyproxy.io/docs/tasks/traffic/direct-response/
#
# NGINX equivalent:
#   nginx.ingress.kubernetes.io/ssl-redirect: 'false'
#   nginx.ingress.kubernetes.io/server-snippet: |-
#     default_type application/json;
#     if ( $scheme = http ){
#       return 400 '{"type": "...", "title": "Bad Request"}';
#     }
#
# Pattern: Reject HTTP requests with 400 JSON error (instead of redirect)
# Use case: API endpoints that require explicit HTTPS (no auto-redirect)

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: http-reject-json
  namespace: ingress2envoygateway
  labels:
    test: server-snippet-25
spec:
  directResponse:
    statusCode: 400
    contentType: "application/json"
    body:
      type: Inline
      inline: '{"type": "https://example.com/errors/400","title": "Bad Request","status": 400, "detail": "Plain HTTP request was sent to the API. Unencrypted HTTP connections are not allowed. Please use HTTPS"}'

# NOTE: For custom-http-errors (intercepting backend errors), use
# BackendTrafficPolicy.responseOverride instead of HTTPRouteFilter.
# HTTPRouteFilter.directResponse is for returning responses WITHOUT backend.
# See: 08-backend-traffic-policy-response-override.yaml for responseOverride config.
