# OAuth2 Test Route - Azure AD Authentication
# ============================================================================
# Test 22: OAuth2 Sign-In (auth-signin)
#
# NGINX Equivalent:
#   nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
#   nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
#
# Prerequisites:
#   1. Azure AD App Registration with redirect URI configured
#   2. Secret 'oidc-client-secret' with key 'client-secret':
#      kubectl create secret generic oidc-client-secret \
#        --from-literal=client-secret='YOUR_AZURE_CLIENT_SECRET' \
#        -n ingress2kgateway
#
# KGateway Native OAuth2 (replaces oauth2-proxy):
#   - GatewayExtension.oauth2 handles the entire OAuth2/OIDC flow
#   - TrafficPolicy.oauth2.extensionRef references the GatewayExtension
#   - No external oauth2-proxy deployment needed
#
# Flow:
#   1. User hits /echo on oauth.${DOMAIN}
#   2. KGateway checks for valid OAuth session (cookie)
#   3. If no session → 302 redirect to Azure AD login
#   4. User authenticates with Azure AD
#   5. Azure AD redirects to /oauth2/callback with auth code
#   6. KGateway exchanges code for token, creates session cookie
#   7. User redirected to original URL (/echo)
#   8. Request proceeds to backend with access token in Authorization header
# ============================================================================

---
# HTTPRoute for OAuth2-protected paths
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oauth2-test-route
  namespace: ingress2kgateway
  labels:
    app: oauth2-test
    test: "22"
spec:
  parentRefs:
  - name: external-gateway
    namespace: ingress2kgateway
    sectionName: https  # Target ONLY the HTTPS listener to avoid port 80 issues
  hostnames:
  - "oauth.${DOMAIN}"
  rules:
  # OAuth2 callback - intercepted by KGateway for token exchange
  - matches:
    - path:
        type: PathPrefix
        value: "/oauth2"
    backendRefs:
    - name: echo-server  # Won't reach backend - intercepted by OAuth2 filter
      port: 8080
  
  # Root redirect (app-root equivalent)
  - matches:
    - path:
        type: Exact
        value: "/"
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          type: ReplaceFullPath
          replaceFullPath: "/echo"
        statusCode: 302
  
  # Protected path - requires OAuth2 authentication
  - matches:
    - path:
        type: PathPrefix
        value: "/echo"
    backendRefs:
    - name: echo-server
      port: 8080
  
  # Logout - clears OAuth session cookie
  - matches:
    - path:
        type: Exact
        value: "/logout"
    backendRefs:
    - name: echo-server
      port: 8080

---
# TrafficPolicy to enable OAuth2 on the route
# Note: Uses oauth2.extensionRef (not extAuth.extensionRef)
#
# CSRF Protection:
#   The OAuth2 filter does not protect against Cross-Site-Request-Forgery attacks
#   on domains with cached authentication (cookies). The CSRF policy validates
#   that the Origin header matches the destination or allowed origins.
#   Reference: KGateway docs recommend pairing OAuth2 with CSRF policy.
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: oauth2-test-policy
  namespace: ingress2kgateway
  labels:
    app: oauth2-test
    test: "22"
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: oauth2-test-route
  
  # Reference the OAuth2 GatewayExtension
  oauth2:
    extensionRef:
      name: oauth2-oidc
  
  # ============================================================================
  # CSRF Protection (recommended for OAuth2)
  # ============================================================================
  # Prevents malicious sites from making authenticated requests using user's cookies.
  # Validates that Origin header matches the destination or additionalOrigins.
  csrf:
    # Enable for 100% of requests
    percentageEnabled: 100
    
    # Optional: Allow additional trusted origins to make cross-origin requests
    # Uncomment and customize for your environment:
    # additionalOrigins:
    # # Exact match - specific trusted domain
    # - exact: "https://trusted-app.example.com"
    # 
    # # Prefix match - all origins starting with this
    # - prefix: "https://internal."
    # 
    # # Suffix match - all origins ending with this domain
    # - suffix: ".${DOMAIN}"
    # 
    # # Contains match - any origin containing this substring
    # - contains: "trusted"
    # 
    # # Regex match - flexible pattern matching
    # - safeRegex: "https://.*\\.mycompany\\.com"
    
    # ============================================================================
    # Alternative: Shadow mode for testing (log but don't enforce)
    # ============================================================================
    # Uncomment to test CSRF without blocking requests:
    # percentageShadowed: 100  # (mutually exclusive with percentageEnabled)
